services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=health_assessment
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - JWT_ALGORITHM=HS256
      - MODEL_SAVE_PATH=/app/models
    volumes:
      - ./backend:/app
      - model_data:/app/models
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  mongodb_data:
  model_data: